[package]
name = "stella-gc"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
log = "0.4"
env_logger = "0.10"
ctor = "0.2"
c-enum = "0.2.3"

[lib]
name = "stella_gc"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
